//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OEHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NokiaComPort {
            get {
                return ((string)(this["NokiaComPort"]));
            }
            set {
                this["NokiaComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ORISid {
            get {
                return ((int)(this["ORISid"]));
            }
            set {
                this["ORISid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".")]
        public string labelWorkingDir {
            get {
                return ((string)(this["labelWorkingDir"]));
            }
            set {
                this["labelWorkingDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int activeTab {
            get {
                return ((int)(this["activeTab"]));
            }
            set {
                this["activeTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tělovýchovná jednota Turnov z.s.")]
        public string organizerIdentificationL1 {
            get {
                return ((string)(this["organizerIdentificationL1"]));
            }
            set {
                this["organizerIdentificationL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ORISSecKey {
            get {
                return ((string)(this["ORISSecKey"]));
            }
            set {
                this["ORISSecKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal rentSIFee {
            get {
                return ((decimal)(this["rentSIFee"]));
            }
            set {
                this["rentSIFee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Skálova 207, Turnov, 511 01")]
        public string organizerIdentificationL2 {
            get {
                return ((string)(this["organizerIdentificationL2"]));
            }
            set {
                this["organizerIdentificationL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IČ: 15045528")]
        public string organizerIdentificationL3 {
            get {
                return ((string)(this["organizerIdentificationL3"]));
            }
            set {
                this["organizerIdentificationL3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Jméno závodu pro doklady - DD.MM.YYYY")]
        public string eventName {
            get {
                return ((string)(this["eventName"]));
            }
            set {
                this["eventName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Datum na pokladni lístek")]
        public string eventDate {
            get {
                return ((string)(this["eventDate"]));
            }
            set {
                this["eventDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Zkratka klubu")]
        public string organizerIdentificationAbbr {
            get {
                return ((string)(this["organizerIdentificationAbbr"]));
            }
            set {
                this["organizerIdentificationAbbr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fromOE {
            get {
                return ((bool)(this["fromOE"]));
            }
            set {
                this["fromOE"] = value;
            }
        }
    }
}
